###########
# site.title

title:    'World of Wordcaft'
subtitle: 'CS 175: Project in Natural Language Processing'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
